import {
  AboutContent,
  ButtonText,
  ContactInfo,
  ContactSocial,
  CoursesCertification,
  ExperienceData,
  Link,
  LogoContent,
  NavLink,
  Project,
  Skill,
  Tab,
} from "@/lib/types";
import {
  AppWindow,
  Award,
  Briefcase,
  Cloud,
  Code,
  Code2,
  Database,
  GitBranch,
  Github,
  GraduationCap,
  House,
  Linkedin,
  Mail,
  MapPin,
  Palette,
  Phone,
  Smartphone,
  User,
  Wrench,
} from "lucide-react";

export const NAV_LINKS: NavLink[] = [
  { name: "Home", href: "#home", icon: House },
  { name: "About", href: "#about", icon: User },
  { name: "Projects", href: "#projects", icon: AppWindow },
  { name: "Skills", href: "#skills", icon: Wrench },
  { name: "Contact", href: "#contact", icon: Mail },
] as const;

export const SOCIAL_LINKS: Link[] = [
  {
    icon: Linkedin,
    href: "https://linkedin.com/in/himanshudkp",
    label: "LinkedIn",
  },
  {
    icon: Github,
    href: "https://github.com/himanshudkp",
    label: "GitHub",
  },
] as const;

export const ABOUT_TABS: Tab[] = [
  { icon: User, id: "about", label: "About" },
  { icon: Briefcase, id: "experience", label: "Experience" },
  { icon: GraduationCap, id: "education", label: "Education" },
  { icon: Award, id: "courses", label: "Courses & Certifications" },
];

export const ABOUT_CONTENT: AboutContent = {
  highlights: [
    "Full-Stack Engineer",
    "2+ years of experience",
    "web",
    "mobile",
    "AI-powered products",
    "React",
    "Next.js",
    "Node.js",
    "FastAPI",
    "Native",
    "healthcare",
    "energy",
    "recruitment",
    "30,000+ users",
    "AI-native products",
    "scalable SaaS platforms",
    "Heaptrace Technology",
    "cross-platform mobile apps",
    "real-time dashboards",
    "backend APIs",
    "LLM-powered features",
  ],
  paragraphs: [
    "I’m a Full-Stack Engineer with 2+ years of experience building and shipping scalable web, mobile, and AI-powered products using React, Next.js, Node.js, FastAPI, and React Native.",
    "At Heaptrace Technology, I worked across healthcare, energy, and recruitment platforms, contributing to systems serving 30,000+ users. I’ve built cross-platform mobile apps, real-time dashboards, backend APIs, and LLM-powered features driving automation and intelligent workflows.",
    "I thrive in fast-moving environments where ownership matters—taking features from idea to production with clean architecture, optimized performance, and secure delivery.",
    "I’m particularly interested in building AI-native products and scalable SaaS platforms where technology directly drives business impact.",
  ],
} as const;

export const EXPERIENCE_DATA: ExperienceData[] = [
  {
    id: "associate",
    title: "Associate Software Developer",
    company: "Heaptrace Technology",
    location: "Pune, India",
    duration: "Dec 2022 - Mar 2025",
    isCurrent: true,
    highlights: [
      "Full-stack engineer",
      "web",
      "mobile",
      "AI-driven platforms",
      "healthcare",
      "energy",
      "recruitment",
      "React",
      "Next.js",
      "Node.js",
      "FastAPI",
      "PostgreSQL",
      "Supabase",
      "OpenAI API",
      "Native",
      "LLM-powered features",
      "secure backend APIs",
      "production systems",
      "30,000+ users",
      "AI-powered recruitment SaaS ",
    ],
    description:
      "Full-stack engineer contributing to scalable web, mobile, and AI-driven platforms across healthcare, energy, and recruitment domains. Built and shipped production systems using React, Next.js, Node.js, and React Native, integrating LLM-powered features and secure backend APIs serving 30,000+ users.",
    projects: [
      {
        name: "Jobbrella",
        description:
          "Built and scaled an AI-powered recruitment SaaS using Next.js, TypeScript, and Node.js. Integrated OpenAI APIs for automated job ad generation and intelligent candidate targeting, reducing ad creation time by 70% and streamlining hiring workflows.",
        link: "#",
      },
      {
        name: "Aevai Health (Alva)",
        description:
          "Developed LLM-integrated healthcare chatbot using SvelteKit, TypeScript, and secure backend services. Enabled structured patient guidance, device setup support, and GDPR-compliant conversational workflows in collaboration with a leading European biobank.",
        link: "#",
      },
      {
        name: "Motkraft",
        description:
          "Engineered cross-platform electricity management app using React Native, Expo, and TypeScript. Built real-time consumption dashboards and secure API integrations, supporting 30,000+ active users with a 4.4/5 satisfaction rating.",
        link: "#",
      },
      {
        name: "GreenFlex",
        description:
          "Developed EV charging and scheduling dashboard using React, Redux Toolkit, and Chart.js. Built dynamic data visualizations and intelligent scheduling system with REST API integration for real-time energy optimization.",
        link: "#",
      },
    ],
    technologies: [
      "React",
      "Next.js",
      "Node.js",
      "React Native",
      "TypeScript",
      "FastAPI",
      "PostgreSQL",
      "Supabase",
      "OpenAI API",
      "Redux Toolkit",
      "TanStack Query",
      "Tailwind CSS",
      "Docker",
      "AWS",
      "Expo",
    ],
  },
] as const;

export const EDUCATION_DATA = [
  {
    id: "pgdmc",
    degree: "Post Graduate Diploma in Mobile Computing (PG-DMC)",
    institution: "Centre for Development of Advanced Computing (CDAC)",
    location: "Pune, India",
    duration: "Mar 2022 - Aug 2022",
    description:
      "Completed intensive post-graduate program focused on mobile application development, cross-platform technologies, and modern JavaScript frameworks. Built hands-on projects using React Native, TypeScript, and backend APIs.",
    highlights: [
      "mobile application development",
      "cross-platform technologies",
      "modern JavaScript frameworks",
    ],
  },
  {
    id: "be",
    degree: "Bachelor of Engineering in Computer Science & Engineering",
    institution: "Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)",
    location: "Bhopal, India",
    duration: "Jul 2013 - Jun 2017",
    description:
      "Earned Bachelor's degree in Computer Science & Engineering with solid foundation in software development principles, algorithms, and database systems. Developed academic projects focusing on web technologies and problem-solving.",
    highlights: [
      "Computer Science & Engineering",
      "web technologies",
      "problem-solving",
    ],
  },
] as const;

export const COURSES_CERTIFICATIONS_DATA: CoursesCertification[] = [
  {
    id: "react-advanced",
    title: "Advanced React Patterns",
    provider: "Frontend Masters",
    issueDate: "Jan 2024",
    credentialId: "FM-2024-001",
    credentialUrl: "#",
    skills: ["React", "TypeScript", "Performance Optimization"],
    description:
      "Advanced patterns and best practices for building scalable React applications.",
  },
  {
    id: "nextjs-mastery",
    title: "Next.js Complete Developer Course",
    provider: "Udemy",
    issueDate: "Nov 2023",
    credentialId: "UC-NEXT-2023",
    credentialUrl: "#",
    skills: ["Next.js", "Server Components", "API Routes"],
    description:
      "Comprehensive course covering Next.js 14, server components, and modern web development.",
  },
  {
    id: "nodejs-backend",
    title: "Node.js Backend Development",
    provider: "Coursera",
    issueDate: "Sep 2023",
    credentialId: "COURSERA-NODE-2023",
    credentialUrl: "#",
    skills: ["Node.js", "Express", "MongoDB", "REST APIs"],
    description:
      "Building scalable backend services with Node.js, Express, and database integration.",
  },
  {
    id: "aws-cloud",
    title: "AWS Certified Cloud Practitioner",
    provider: "Amazon Web Services (AWS)",
    issueDate: "Jul 2023",
    credentialId: "AWS-CCP-2023-789",
    credentialUrl: "#",
    skills: ["AWS", "Cloud Computing", "Deployment"],
    description:
      "Foundational understanding of AWS Cloud services and deployment strategies.",
  },
  {
    id: "openai-api",
    title: "Building AI Apps with OpenAI API",
    provider: "DeepLearning.AI",
    issueDate: "May 2023",
    credentialId: "DL-AI-2023-456",
    credentialUrl: "#",
    skills: ["OpenAI API", "LLM Integration", "AI Development"],
    description:
      "Integrating OpenAI APIs to build intelligent, AI-powered applications.",
  },
  {
    id: "react-native",
    title: "React Native - The Practical Guide",
    provider: "Udemy",
    issueDate: "Mar 2023",
    credentialId: "UC-RN-2023-123",
    credentialUrl: "#",
    skills: ["React Native", "Expo", "Mobile Development"],
    description:
      "Complete guide to building cross-platform mobile applications with React Native.",
  },
] as const;

export const PROJECTS_TABS: Tab[] = [
  { icon: AppWindow, id: "all", label: "All" },
  { icon: Code, id: "frontend", label: "Frontend" },
  { icon: Cloud, id: "backend", label: "Backend" },
  { icon: Smartphone, id: "mobile", label: "Mobile" },
  { icon: Database, id: "fullstack", label: "Fullstack" },
];

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: "Jobbrella",
    shortDesc: "AI-Powered Recruitment Platform for modern hiring",
    image:
      "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80",
    topTools: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "TanStack Query",
      "Socket.IO",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
    ],
    fullDescription:
      "Built and maintained responsive, brand-aligned UIs for a comprehensive recruitment platform.",
    features: [
      "Dynamic job ad creation with AI-powered content generation",
      "Real-time candidate tracking and management system",
      "Optimistic UI updates with TanStack Query",
    ],
    allTech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "TanStack Query",
      "Socket.IO",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "TanStack Query",
      "Socket.IO",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
    ],
    githubUrl: "#",
    liveUrl: "#",
    categories: ["frontend", "fullstack"],
  },
  {
    id: 2,
    title: "Motkraft",
    shortDesc: "Real-time Electricity Consumption Tracking Platform",
    image:
      "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80",
    topTools: [
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "TanStack Query",
      "Socket.IO",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
    ],
    fullDescription:
      "Developed comprehensive mobile and web applications enabling 30K+ users.",
    features: [
      "Multi-meter onboarding system",
      "Real-time electricity consumption monitoring",
      "Interactive visualizations",
    ],
    allTech: [
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "TanStack Query",
      "Socket.IO",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
    ],
    githubUrl: "#",
    liveUrl: "#",
    categories: ["mobile", "fullstack"],
  },
  {
    id: 3,
    title: "GreenFlex",
    shortDesc: "EV Charging & Scheduling Dashboard Solution",
    image:
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80",
    topTools: [
      "React.js",
      "React Native",
      "TypeScript",
      "Redux Toolkit",
      "Chart.js",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Expo",
    ],
    fullDescription:
      "Developed the GreenFlex EV Charging Dashboard with dynamic data visualizations.",
    features: [
      "Real-time EV charging status monitoring",
      "Dynamic data visualization",
      "Intelligent scheduling system",
    ],
    allTech: [
      "React.js",
      "React Native",
      "TypeScript",
      "Redux Toolkit",
      "Chart.js",
    ],
    githubUrl: "#",
    liveUrl: "#",
    categories: ["mobile", "fullstack"],
  },
];

export const CONTACT_INFO: ContactInfo[] = [
  {
    icon: Mail,
    text: "himanshudkp@gmail.com",
    href: "mailto:himanshudkp@gmail.com",
  },
  { icon: Phone, text: "+91 9522498034", href: "tel:+919522498034" },
  { icon: MapPin, text: "Pune, India", href: "#" },
];

export const SOCIALS: ContactSocial[] = [
  { icon: Github, href: "#" },
  { icon: Linkedin, href: "https://linkedin.com/in/himanshudkp" },
];

export const LOGO_CONTENT: LogoContent = {
  name: "Himanshu",
  initials: "H",
} as const;

export const BUTTON_TEXT: ButtonText = {
  resume_web: "Resume",
  resume_mobile: "Resume",
  connect: "Connect",
  work: "My Work",
};

export const QUICK_LINKS = [
  { name: "About", href: "#about" },
  { name: "Experience", href: "#experience" },
  { name: "Projects", href: "#projects" },
  { name: "Skills", href: "#skills" },
  { name: "Contact", href: "#contact" },
];

export const SKILLS_TABS: Tab[] = [
  { id: "all", label: "All", icon: AppWindow },
  { id: "frontend", label: "Frontend", icon: Code2 },
  { id: "mobile", label: "Mobile", icon: Smartphone },
  { id: "styling", label: "Styling", icon: Palette },
  { id: "state", label: "State Management", icon: Database },
  { id: "backend", label: "Backend & Database", icon: Cloud },
  { id: "tools", label: "Tools & DevOps", icon: GitBranch },
];

export const SKILLS: Skill[] = [
  { category: ["frontend", "all"], skill: "ReactJS" },
  { category: ["frontend", "all"], skill: "Next.js" },
  { category: ["frontend", "all"], skill: "TypeScript" },
  { category: ["frontend", "all"], skill: "JavaScript" },
  { category: ["frontend", "all"], skill: "HTML/CSS" },
  { category: ["mobile", "all"], skill: "React Native" },
  { category: ["mobile", "all"], skill: "Expo" },
  { category: ["mobile", "all"], skill: "iOS Development" },
  { category: ["mobile", "all"], skill: "Android Development" },
  { category: ["styling", "all"], skill: "Tailwind CSS" },
  { category: ["styling", "all"], skill: "SCSS" },
  { category: ["styling", "all"], skill: "Material UI" },
  { category: ["styling", "all"], skill: "Shadcn UI" },
  { category: ["styling", "all"], skill: "Responsive Design" },
  { category: ["state", "all"], skill: "Redux Toolkit" },
  { category: ["state", "all"], skill: "TanStack Query" },
  { category: ["state", "all"], skill: "Context API" },
  { category: ["backend", "all"], skill: "Node.js" },
  { category: ["backend", "all"], skill: "PostgreSQL" },
  { category: ["backend", "all"], skill: "Supabase" },
  { category: ["backend", "all"], skill: "REST APIs" },
  { category: ["backend", "all"], skill: "Socket.IO" },
  { category: ["tools", "all"], skill: "Git/GitHub" },
  { category: ["tools", "all"], skill: "VS Code" },
  { category: ["tools", "all"], skill: "Postman" },
  { category: ["tools", "all"], skill: "Vercel" },
  { category: ["tools", "all"], skill: "Performance Optimization" },
];
